[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
    theme = "nightfall"
[params]
  user = "vachan"
  hostname = " "
  description = "Hey there! I am Vachan and I love thinkering with computers. I am currently pursuing Computer Science and Engineering. You can read my posts, know more about me and get in touch with me"
    [params.author]
    name = "Vachan S Panicker"
    email = "vachan@tutanota.com"


[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"

  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

[[params.social]]
key = 0
name = "GitHub"
url = "https://github.com/vachan-maker"

[[params.social]]
key = 1
name = "Mastodon"
url = "https://fosstodon.org/@nattukaran"
rel = "me"

[[params.social]]
key = 2
name = "E-mail"
url = "mailto:vachan@tutanota.com"

[[params.social]]
key = 3
name = "PixelFed"
url = "https://pixelfed.social/V4vachan"

[[params.social]]
key = 4
name = "RSS Feed"
url = "/index.xml"
[[params.social]]
key = 5
name = "X"
url = "https://twitter.com/vsp2020"



